name: Bug report
description: File a bug
labels: [bug]
body:
  - type: input
    id: version
    attributes: { label: Version/commit }
  - type: textarea
    id: repro
    attributes: { label: Repro steps }
  - type: textarea
    id: expected
    attributes: { label: Expected }
  - type: textarea
    id: actual
    attributes: { label: Actual / logs }
